baseurl = "/"
languageCode = "en-us"
title = "Aspendell.org"
theme = "hugo-creative-theme"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "./img/aspen_leaf.png"


	# Navigation
	[params.navigation]
		brand = "APOA Website" # Put something here for upper left header

		[params.navigation.links]
		  events    = "Events"
		  conditions = "Weather & Road"
		  asfvfd = "ASFVFD"
		  information = "About Aspendell"
		  localtips = "Useful Information"
		  gallery = "Photos"
			contact   = "Contact"



	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "ASPENDELL"
		subtitle   = "Bishop, CA 93514"
		# buttonText = "Find out more"


  # Events section
	[params.events]
		headline    = "Upcoming events:"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started!"

	# Road & weather section
	[params.conditions]
		headline    = "Conditions:"

	# About Aspendell section
	[params.information]
		headline    = "Upcoming events:"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Get started!"

# Local resources section
	[params.localtips]
		headline    = "local tips something"

# Photo gallery
	[params.gallery]
		headline    = "photo gallery"

# ASFVFD section
	[params.asfvfd]
		headline    = "volunteer fire"

	# About section
	# [params.about]
	#	headline    = "We've got what you need!"
	#	description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
	#	buttonText  = "Get started!"

	# Service section
	# [params.services]
	#	headline = "At your service"

  #      [[params.services.list]]
  #          icon = "fa-diamond"
  #          title = "Sturdy Templates"
   #         description = "Our templates are updated regularly so they don't break."

  #     [[params.services.list]]
	#		icon = "fa-paper-plane"
	#		title = "Ready to Ship"
	#		description = "You can use this theme as is, or you can make changes!"

	#	[[params.services.list]]
  #          icon = "fa-newspaper-o"
  #          title = "Up to Date"
  #          description = "We update dependencies to keep things fresh."

  #      [[params.services.list]]
  #          icon = "fa-heart"
  #          title = "Made with Love"
  #          description = "You have to make your websites with love these days!"


    # Portfolio modals
	#[params.portfolio.modal]
  #      client = "Client"
  #      date = "Date"
  #      category = "Category"
  #      buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Get the Creative Theme for Hugo"

	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	# [params.contact]
	#	headline = "Contact us to receive updates from the APOA"
	#	email = "shareinfo@aspendell.org"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
